version: '3.8'

networks:
  test:
    external: true

services:
  postgres:
    image: postgres:15
    container_name: consumer_postgres
    environment:
      POSTGRES_DB: consumer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    networks:
      - test

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cus_rabbitmq
    ports:
      - "5695:5672"
      - "15695:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - test
